### ISSUE TITLE
Error Culqi\Error\UnhandledError

### ISSUE THREAD

**Issue by amquisher** [culqi/culqi-php#26]
Buen día, ya he logrado probar la aplicacion con las tarjetas de prueba que ofrecen y todo sale Ok,
 sin embargo al usar las Tarjetas con respuestas y errores específicos, solo la primera que es " expired_card" me devuelve el error con el json, el resto me sale la siguiente Exception...

`message: {"object":"error","type":"card_error","charge_id":"chr_test_1zMFFuuJgRayHWHN","code":"card_declined","merchant_message":"Fondos insuficientes. La tarjeta no tiene fondos suficientes para realizar la compra.","user_message":"Su tarjeta no tiene fondos suficientes. Para realizar la compra, verifica tus fondos disponibles con el banco emisor o inténta nuevamente con otra tarjeta."}
exception: Culqi\Error\UnhandledError
file: /Users/angel/Code/cart/vendor/culqi/culqi-php/lib/Culqi/Client.php
line: 49`

Saludos.

**Comment by LizRuelas** [comment]
Hola @amquisher proporcionarme las tarjetas con las cuales tienes inconvenientes a integrate@culqi.com Saludos

**Comment by brayhanlt2** [comment]
Buen día, tengo el mismo problema Culqi\Error\UnhandledError  en el archivo Client.php en la línea 52.
Pero a mí me devuelve el objeto asi:
"<br />
<b>Fatal error</b>:  Uncaught Culqi\Error\UnhandledError: {&quot;object&quot;:&quot;error&quot;,&quot;type&quot;:&quot;card_error&quot;,&quot;charge_id&quot;:&quot;chr_test_A1CtKQIL82xpP848&quot;,&quot;code&quot;:&quot;card_declined&quot;,&quot;decline_code&quot;:&quot;insufficient_funds&quot;,&quot;merchant_message&quot;:&quot;Fondos insuficientes. La tarjeta no tiene fondos suficientes para realizar la compra.&quot;,&quot;user_message&quot;:&quot;Su tarjeta no tiene fondos suficientes. Para realizar la compra, verifica tus fondos disponibles con el banco emisor o inténta nuevamente con otra tarjeta.&quot;} in C:\xampp\htdocs\Optimize\public\culqi\lib\Culqi\Client.php:52
Stack trace:
#0 C:\xampp\htdocs\Optimize\public\culqi\lib\Culqi\Charges.php(29): Culqi\Client-&gt;request('POST', '/charges/', 'sk_test_jydu6ZW...', Array)
#1 C:\xampp\htdocs\Optimize\ajax.php(187): Culqi\Charges-&gt;create(Array)
#2 {main}
  thrown in <b>C:\xampp\htdocs\Optimize\public\culqi\lib\Culqi\Client.php</b> on line <b>52</b><br />".

Esto solo pasa cuando pruebo una tarjeta con error, porque las tarjetas de prueba sin error las procesa y devuelve un objeto con los datos correctamente.

**Comment by fecori** [comment]
Hola, tengo el mismo error y la unica salida que he tenido es agregar la siguiente linea:

`if ($response->status_code == 402) {
            return json_decode($response->body);
        }`
Espero que este parche sea temporal hasta nos den una solucion.

Saludos.

**Comment by DavmanHack** [comment]
Hola fecori, donde llegast a poner esa linea?

**Comment by fecori** [comment]
> Hola fecori, donde llegast a poner esa linea?

Hola @DavmanHack esa linea la puse en la libreria que se instala en el vendor de laravel

culqi\lib\Culqi\Client.php

**Comment by joelibaceta** [comment]
Voy a revisar lo comentan en este issue, @fecori el PR de tu solución temporal es bienvenido 👍

**Comment by kadmik** [comment]
Hola, yo tengo el mismo problema, con las tarjetas de prueba de éxito, todo funciona bien, pero para ver los errores de las tarjetas con error, me sale el mismo error que @brayhanlt2 
@fecori por favor, me podrías decir en que línea agregaste lo que mencionaste?

Gracias.

**Comment by kalin79** [comment]
Muchas gracias tambien tuve el mismo problema ....
