### ISSUE TITLE
Error en el formulario de pago

### ISSUE THREAD

**Issue by d2magicos** [culqi/culqi-php#68]
index-C7zDswTy.js:13 TypeError: Cannot read properties of undefined (reading 'importKey')
    at Aq (index-C7zDswTy.js:77:702)
    at _k (index-C7zDswTy.js:77:1215)
    at Lk.getSession (index-C7zDswTy.js:77:1884)
    at at.getSessionId (index-C7zDswTy.js:77:8174)
    at F (index-C7zDswTy.js:77:16919)
    at Proxy.Y (index-C7zDswTy.js:77:16885)
    at Proxy.<anonymous> (index-C7zDswTy.js:17:13292)
    at Z (index-C7zDswTy.js:77:100938)
    at X (index-C7zDswTy.js:77:100865)
    at Er (index-C7zDswTy.js:13:38)

Porque me esta saliendo este error al momento de colocar la tarjeta en el formulario de prueba

**Comment by soporte-culqi** [comment]
Hola, Jordan:
 
 ¡Gracias por comunicarte con nosotros!
 
 Hemos recibido tu solicitud y la atenderemos a la brevedad posible. Sin embargo, es necesario que puedas brindanos los siguientes datos:
 
 RUC:
 Razón social:
 Web:
 
 Recuerda que si necesitas mayor información acerca de nuestros procesos puedes consultar nuestras preguntas frecuentes o dirigirte a tu CulqiPanel para consultar sobre tus ventas y/o abonos. 
 Saludos,
 
 Elizabeth G. Equipo Culqi
 
 
 
 
 
 
 
---- en Lunes, 18 Mar 2024 09:47:20 -0500 ***@***.***> escribió ---- 
 index-C7zDswTy.js:13 TypeError: Cannot read properties of undefined (reading 'importKey')
 at Aq (index-C7zDswTy.js:77:702)
 at _k (index-C7zDswTy.js:77:1215)
 at Lk.getSession (index-C7zDswTy.js:77:1884)
 at at.getSessionId (index-C7zDswTy.js:77:8174)
 at F (index-C7zDswTy.js:77:16919)
 at Proxy.Y (index-C7zDswTy.js:77:16885)
 at Proxy. (index-C7zDswTy.js:17:13292)
 at Z (index-C7zDswTy.js:77:100938)
 at X (index-C7zDswTy.js:77:100865)
 at Er (index-C7zDswTy.js:13:38) Porque me esta saliendo este error al momento de colocar la tarjeta en el formulario de prueba —

**Comment by d2magicos** [comment]
A que correo envio esta información?
